alocar_funcionario_(1)/config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :funcionarios
  resources :clientes

end

alocar_funcionario_(1)/app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

alocar_funcionario_(1)/app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
end

alocar_funcionario_(1)/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

alocar_funcionario_(1)/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente criado com sucesso.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente removido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :local)
    end
end

alocar_funcionario_(1)/app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
    @cliente = Cliente.find @funcionario.cliente_id
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
    @clientes = Cliente.all
    respond_to do |format|
      format.html
    end
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario criado com sucesso.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario removido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :registro, :setor, :cliente_id)
    end
end

alocar_funcionario_(1)/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

alocar_funcionario_(1)/app/helpers/application_helper.rb
module ApplicationHelper
end

alocar_funcionario_(1)/app/helpers/clientes_helper.rb
module ClientesHelper
end

alocar_funcionario_(1)/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

alocar_funcionario_(1)/app/helpers/main_helper.rb
module MainHelper
end

alocar_funcionario_(1)/app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :local %><br>
    <%= f.text_field :local %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

alocar_funcionario_(1)/app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @cliente %> |
<%= link_to 'Voltar', clientes_path %>

alocar_funcionario_(1)/app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Local</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.local %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Remover', cliente, method: :delete, data: { confirm: 'Deseja remover?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cliente', new_cliente_path %>
<%= link_to 'Voltar', { :controller => "main" } %>

alocar_funcionario_(1)/app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', clientes_path %>

alocar_funcionario_(1)/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Local:</strong>
  <%= @cliente.local %>
</p>

<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Voltar', clientes_path %>

alocar_funcionario_(1)/app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario) do |f| %>
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :registro %><br>
    <%= f.text_field :registro %>
  </div>
  <div class="field">
    <%= f.label :setor %><br>
    <%= f.text_field :setor %>
  </div>
  <div class="field">
    <%= f.label :cliente_id %><br>
    <%= collection_select(:funcionario, :cliente_id, @clientes, :id, :local, {:prompt => false}) %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

alocar_funcionario_(1)/app/views/funcionarios/edit.html.erb
<h1>Editing Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

alocar_funcionario_(1)/app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Funcionarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Registro</th>
      <th>Setor</th>
      <th>Cliente ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.registro %></td>
        <td><%= funcionario.setor %></td>
        <td><%= funcionario.cliente_id %></td>
        <td><%= link_to 'Mostrar', funcionario %></td>
        <td><%= link_to 'Editar', edit_funcionario_path(funcionario) %></td>
        <td><%= link_to 'Remover', funcionario, method: :delete, data: { confirm: 'Deseja remover?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Funcionario', new_funcionario_path %>
<%= link_to 'Voltar', { :controller => "main" } %>

alocar_funcionario_(1)/app/views/funcionarios/new.html.erb
<h1>New Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Voltar', funcionarios_path %>

alocar_funcionario_(1)/app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Registro:</strong>
  <%= @funcionario.registro %>
</p>

<p>
  <strong>Setor:</strong>
  <%= @funcionario.setor %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @cliente.nome %>
</p>

<%= link_to 'Editar', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Voltar', funcionarios_path %>

alocar_funcionario_(1)/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlocarFuncionario</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

alocar_funcionario_(1)/app/views/main/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bem-vindo</h1>

<br>

<ul>
  <li>
    <%= link_to 'Manter Cliente', clientes_path %>
  </li>
  <li>
    <%= link_to 'Manter Funcionário', funcionarios_path %>
  </li>
</ul>